### ISSUE TITLE
Code Stability

### ISSUE THREAD

**Issue by rachel-1** [zuoxingdong/lagom#176]
I noticed that this repo is under extremely active development (so props to you for putting so much time in). I've started to use this framework as a basis for my current RL research project, but I don't want to lose compatibility every few days or risk pulling breaking code. For example, currently `td3/experiment.py` doesn't work because of the refactor from `num_worker` to `max_workers` in `run_experiment`. 

What is the roadmap for development? For example, is Tensorboard logging in the works? 

I'm using PPO and TD3 in particular; Is there a particular commit I should stick to while things stabilize?

**Comment by zuoxingdong** [comment]
@rachel-1 Thank you very much for your kind message and interest in this repo. Indeed, there'd been quite active developments in the past, in fact, I am towards an end to finalize the baselines of coming release. Now all baselines except for TD3 should be synchronized to the latest infrastructure. Now I am running benchmarking of ES and DDPG & SAC.

Approximately by Friday this week, all the baselines should be finalized and ship to a stable release `v0.1.0`. For PPO, I think you can already use the current version in master branch, it won't be changed drastically anymore. For TD3, I'll fix the code by tomorrow and then it should be ready to use. 

Thanks again for your appreciation of this code base and you're highly welcomed to leave any comment/question regarding the implementation. :)

**Comment by rachel-1** [comment]
Okay sounds good! I asked about Tensorboard logging in particular, because I will likely be adding it for myself over the next few days and wanted to make sure I wasn't duplicating any work.

**Comment by zuoxingdong** [comment]
Hi @rachel-1 , Tensorboard is not yet supported in this code base for now, free feel to adapt the code to use it. btw, as you may already know, from PyTorch 1.1.0 that released a few days ago, Tensorboard is officially supported by PyTorch.

**Comment by rachel-1** [comment]
Yeah I've heard about the new PyTorch release; I just wasn't sure how much would break if I upgraded. I'll go ahead and play around a bit :)

**Comment by zuoxingdong** [comment]
Hi @rachel-1 , now the TD3 is synchronized to latest refactoring, and should be ready for use. Except for bug fixes, there wouldn't be any further modifications.
