### ISSUE TITLE
make mujoco an optional dependence

### ISSUE THREAD

**Issue by CarloLucibello** [zuoxingdong/lagom#198]
Since mujoco is non-free, this would be much convenient for people not interested in it

**Comment by zuoxingdong** [comment]
Hi @CarloLucibello , indeed, it's quite annoying that Mujoco requies commercial license. But installing the repo does not force the Mujoco dependency, just the baselines examples are pre-trained with Mujoco. The motivation is to make it convenient for RL research community to quickly prototype their idea with minimal modification of the code. 

However, using it with non-Mujoco environment should be fair easy, just simply change the configuration `'end.id'`.

**Comment by CarloLucibello** [comment]
ops, sorry, I got confused, I was running the wrong environment
